name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo bin
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin
    - name: Install cbc
      run: sudo apt-get install coinor-libcbc-dev 
    - name: Test
      run: make test
  nits:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo deadlinks
      run: |
        curl -L -o ~/.cargo/bin/cargo-deadlinks https://github.com/deadlinks/cargo-deadlinks/releases/download/0.4.2/deadlinks-linux
        chmod +x ~/.cargo/bin/cargo-deadlinks
        cargo deadlinks --version
    - name: Nits
      run: make nits
  codspeed:
    runs-on: ubuntu-latest
    needs: [ test, nits ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: 1.76.0
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo +1.76.0 codspeed build --features codspeed-criterion-compat

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: cargo codspeed run

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3